services:
  my-server:
    build: .
    ports:
      - 8080:8080
    depends_on:
      ticketflow-db:
        condition: service_healthy

  ticketflow-db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: ticketflow
    volumes:
      - ./mysql_data:/var/lib/mysql
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD", "mysqladmin", "ping"]
      interval: 5s
      retries: 10